### ISSUE TITLE
Package Management Module

### ISSUE THREAD

**Issue by ievans** [dormbase/dormbase#15]
Dormbase needs a module to manage packages. The module should have the following features:
- allow high speed package entry for deskworkers (let them use the fast directory search to quickly find the resident in question)
- provide a mechanism whereby the deskworkers can defer finalizing the package entry until they've been presented with all of the packages entered under that user and confirmed it. The "you have packages" email should be sent  after this confirmation.
- allow desk workers to mark a package as picked up
- keep track of when packages arrived and when they were picked up
- allow users to see how many packages they have outstanding and when they arrived

**Comment by dlukeomalley** [comment]
Base functionality is done. Was decided that some of these features are enhancements and not needed at this time.
