### ISSUE TITLE
Today's Dining

### ISSUE THREAD

**Issue by achernya** [dormbase/dormbase#2]
Bon Appétit has a website (http://www.cafebonappetit.com/menu/your-cafe/mit) that shows the menu for each day. Dormbase should import the menu and display it in a convenient way.

**Comment by ievans** [comment]
The scraping should happen from the rss feed (http://www.cafebonappetit.com/rss/menu/402)

**Comment by achernya** [comment]
...which still has HTML in it. _facepalm_

**Comment by ievans** [comment]
Oooh! Let's use regex to parse the HTML! Kidding, kidding.

Sent from my iPhone

On Apr 21, 2012, at 11:26 PM, Alex Chernyakhovsky
reply@reply.github.com
wrote:

**Comment by DrewDennison** [comment]
Raw HTML is now dumped to page. It should be stripped and properly stylized

**Comment by dlukeomalley** [comment]
Feature is in place now. Can be improved later. I'm closing this issue.
